### ISSUE TITLE
Unhandled Exception: System.BadImageFormatException

### ISSUE THREAD

**Issue by CodeFanaticX** [0xb11a1/yetAnotherObfuscator#2]
Is this not compatible for .NET Core or console app? or just .NET Framework app?

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'file:///D:\app.exe' or one of its dependencies. The module was expected to contain an assembly manifest.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at yetAnotherObfuscator.Program.Main(String[] args) in D:\yetAnotherObfuscator\yetAnotherObfuscator\Program.cs:line 26
```

**Comment by 0xb11a1** [comment]
yes it only works on .Net Framework apps
